# -*- coding: utf-8 -*-
"""EDA SICRO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZNkn2gKIquCwMxTt9lssXl2MNW9ZFMBN

# Importação e visualização inicial da base de dados
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

sicro = pd.read_csv("/content/SICRO_COMPLETO_2022-2024.csv", encoding="latin1")

sicro.info()

sicro.head()

sicro.tail()

sicro.describe().T

sicro.isnull().sum()

"""---

# Limpeza e seleção do grupo a ser analisado
"""

sicro = sicro.dropna()
sicro.isnull().sum()

print(sicro['TipoInsumo'].value_counts())

mdo_df = sicro[sicro["TipoInsumo"] == "Mão de obra"][["DESCRIÇÃO", "UNIDADE", "UF", "Preço.Entregue", "Preço.Final", "REF", "PEI", "Região"]]

mdo_df.to_csv('mdo_df.csv', index=False)

print(mdo_df['PEI'].value_counts())

mdo_df.reset_index()

"""----------------

# Estatísticas gerais do preço da mão de obra
"""

mdo_df.describe().T

media_geral = round(mdo_df['Preço.Final'].mean(), 3)
mediana_geral = round(mdo_df['Preço.Final'].median(), 3)
dp_geral = round(mdo_df['Preço.Final'].std(ddof=1), 3)
vr_geral = round(mdo_df['Preço.Final'].var(ddof=1), 3)
amp_abs_geral = round(mdo_df["Preço.Final"].max() - mdo_df["Preço.Final"].min(), 3)
amp_rel_geral = round(amp_abs_geral / media_geral * 100, 3)
iqr_geral = round(mdo_df["Preço.Final"].quantile(0.75) - mdo_df["Preço.Final"].quantile(0.25), 3)


print(f"RESUMO ESTATÍSTICO")

resumo_geral = {
    'Média geral dos preços': [media_geral],
    'Mediana geral dos preços': [mediana_geral],
    'Desvio padrão geral dos preços': [dp_geral],
    'Variância geral dos preços': [vr_geral],
    'Amplitude absoluta geral dos preços': [amp_abs_geral],
    'Amplitude relativa geral dos preços': [f"{amp_rel_geral}%"],
    'Intervalo interquartil geral dos preços': [iqr_geral]
}

resumo_geral = pd.DataFrame(resumo_geral)

display(resumo_geral)

"""Desvio padrão alto, intervalo interquartil alto, media e mediana bem distantes"""

mdo_df.groupby('PEI')[["DESCRIÇÃO", "UNIDADE", "UF", "REF", "Região"]].agg(lambda x:pd.Series.mode(x))

"""Região mais frequente é o Nordeste"""

mdo_df["zscore"] = (mdo_df["Preço.Final"] - media_geral) / (dp_geral)
display(mdo_df)

outliers_geral = mdo_df[(mdo_df["zscore"] >= 2) | (mdo_df["zscore"] <= -2)]
proporcao_outliers = len(outliers_geral) / len(mdo_df) * 100

print(f"Quantidade de outliers na população: {len(outliers_geral)}\nProporção de outliers na amostra: {proporcao_outliers:.2f}%")

"""Quantidade proporcional de outliers um pouco alta, deveria estar em torno de 4 a 5%"""

mdo_df['REF'] = mdo_df['REF'].astype(str)

ref_ordenado = sorted(mdo_df["REF"].unique())

plt.figure(figsize=(10,8))
sns.lineplot(
    data=mdo_df,
    x="REF",
    y="Preço.Final",
    marker="o",
    color="indigo"
)

plt.xticks(ref_ordenado, rotation=45)

plt.title("Evolução do preço da mão de obra")
plt.xlabel("Meses")
plt.ylabel("Preço")
plt.tight_layout()
plt.show()

"""Tendência de aumento, com pequenas quedas em julho de 2022 e 2023"""

plt.figure(figsize=(6,4))
sns.barplot(data=mdo_df, x="Região", y="Preço.Final", estimator="mean")
plt.title("Preço médio por Região de mão de obra")
plt.xlabel("Região")
plt.ylabel("Preço médio")
plt.show()

"""Sudeste com maior média, e centro-oeste com menor média"""

plt.figure(figsize=(15,30))
sns.countplot(
    data=mdo_df,
    y="DESCRIÇÃO",
    order=mdo_df["DESCRIÇÃO"].value_counts().index,
    palette="cividis"
)
plt.title("Contagem por descrição do tipo da mão de obra")
plt.xlabel("Contagem")
plt.ylabel("Tipo da mão de obra")
plt.show()

"""Variação entre o tipo de mão de obra não é tão grande, tendo muitas muito frequentes, e poucas com frequência baixa"""

plt.figure(figsize=(6,4))
sns.histplot(
    mdo_df["Preço.Final"],
    bins=30,
    color="gold"
)
plt.title("Histograma do preço")
plt.xlabel("Preço")
plt.ylabel("Frequência")
plt.show()

"""Preços mais concentrados a esquerda, valores mais baixos"""

plt.figure(figsize=(10,8))
sns.boxplot(
    data=mdo_df,
    y="Preço.Final",
    palette="Set3"
)

plt.yscale("log")
plt.title("Boxplot de preços da mão de obra")
plt.ylabel("Preço")
plt.show()

"""Valores concetrados entre o primeiro quartil e a mediana"""

plt.figure(figsize=(6,4))
sns.scatterplot(
    data=mdo_df,
    x="Preço.Final",
    y="Preço.Entregue",
    alpha=0.1,
    palette="tab20"
)
plt.title("Preço Final vs. Preço Entregue")
plt.xlabel("Preço Final")
plt.ylabel("Preço Entregue")
plt.show()

"""Correlação 100%"""

plt.figure(figsize=(6,4))
sns.scatterplot(
    data=mdo_df,
    x="Preço.Final",
    y="zscore",
    alpha=0.1,
    palette="tab20"
)
plt.title("Preço Final vs. Zscore")
plt.xlabel("Preço Final")
plt.ylabel("Zscore")
plt.show()

"""Correlação 100%"""

corr = mdo_df[["Preço.Final", "Preço.Entregue"]].corr()

plt.figure(figsize=(6,5))
sns.heatmap(
    corr,
    annot=True,
    cmap="coolwarm",
    vmin=-1,
    vmax=1,
    linewidths=0.5
)
plt.title("Matriz de Correlação entre Prelo Final e Preço Entregue")
plt.tight_layout()
plt.show()

"""Correlação 100%"""

corr = mdo_df[["Preço.Final", "zscore"]].corr()

plt.figure(figsize=(6,5))
sns.heatmap(
    corr,
    annot=True,
    cmap="coolwarm",
    vmin=-1,
    vmax=1,
    linewidths=0.5
)
plt.title("Matriz de Correlação entre Preço Final e Zscore")
plt.tight_layout()
plt.show()

"""Correlação 100%

---

# Estatísticas da mão de obra por região
"""

freq_abs_reg = mdo_df['Região'].value_counts()
freq_rel_reg = mdo_df['Região'].value_counts(normalize=True)*100

media_regiao = round(mdo_df.groupby('Região')['Preço.Final'].mean(), 3)
mediana_regiao = round(mdo_df.groupby('Região')['Preço.Final'].median(), 3)
dp_regiao = round(mdo_df.groupby('Região')['Preço.Final'].std(ddof=1), 3)
vr_regiao = round(mdo_df.groupby('Região')['Preço.Final'].var(ddof=1), 3)
amp_abs_regiao = round(mdo_df.groupby('Região')["Preço.Final"].max() - mdo_df.groupby('Região')["Preço.Final"].min(), 3)
amp_rel_regiao = round((amp_abs_regiao /  media_regiao)* 100, 3)
iqr_regiao = round(mdo_df.groupby('Região')["Preço.Final"].quantile(0.75) - mdo_df.groupby('Região')["Preço.Final"].quantile(0.25), 3)

resumo_regiao = pd.concat([
    freq_abs_reg.rename("Frequência Absoluta"),
    freq_rel_reg.rename("Frequência Relativa"),
    media_regiao.rename("Média"),
    mediana_regiao.rename("Mediana"),
    dp_regiao.rename("Desvio Padrão"),
    vr_regiao.rename("Variância"),
    amp_abs_regiao.rename("Amplitude Absoluta"),
    amp_rel_regiao.rename("Amplitude Relativa"),
    iqr_regiao.rename("IQR")
], axis=1)

resumo_regiao["Frequência Relativa"] = resumo_regiao["Frequência Relativa"].astype(str) + "%"
resumo_regiao["Amplitude Relativa"] = resumo_regiao["Amplitude Relativa"].astype(str) + "%"

display(resumo_regiao)

mdo_df.groupby('Região')[["UNIDADE", "UF", "REF", "PEI"]].agg(lambda x:pd.Series.mode(x))

plt.figure(figsize=(10, 6))
sns.lineplot(
    data=mdo_df,
    x="REF",
    y="Preço.Final",
    hue="Região",
    style="Região",
    markers=True,
    dashes=False,
    ci=None
)

plt.xticks(rotation=45)
plt.title("Evolução do preço da mão de obra por região")
plt.xlabel("Meses")
plt.ylabel("Preço")
plt.tight_layout()
plt.show()

"""Tendencia geral igual, mas sudeste e norte parecem ter mais picos, e centro-oeste aumentou bastante temporalmente"""

plt.figure(figsize=(10, 6))
sns.histplot(
    data = mdo_df,
    x = "Preço.Final",
    hue="Região",
    multiple="dodge",
    bins=10,
    palette="husl"
)

plt.title("Histograma do preço final por região")
plt.xlabel("Preço")
plt.ylabel("Frequência")
plt.show()

"""Nordeste e Norte concentram valores de preços mais baixos"""

plt.figure(figsize=(14,12))
sns.boxplot(
    data=mdo_df,
    x="Região",
    y="Preço.Final",
    palette="colorblind"
)

plt.yscale("log")
plt.title("Boxplot de preços da mão de obra por região")
plt.xlabel("Região")
plt.ylabel("Preço")
plt.show()

"""Caixas mais altas no sudeste principlamente, e medianas mais altas no sul e sudeste"""

outliers_regiao = outliers_geral.groupby('Região').size()

plt.figure(figsize=(8, 5))
plt.barh(outliers_regiao.index, outliers_regiao.values)
plt.title("Quantidade de Outliers por Região")
plt.xlabel("Quantidade de Outliers")
plt.ylabel("Região")
plt.tight_layout()
plt.show()

"""Muitos outliers no Nordeste

---

# Estatísticas da mão de obra por unidade federativa
"""

freq_abs_uf = mdo_df['UF'].value_counts()
freq_rel_uf = mdo_df['UF'].value_counts(normalize=True)*100

media_uf = round(mdo_df.groupby('UF')['Preço.Final'].mean(), 3)
mediana_uf = round(mdo_df.groupby('UF')['Preço.Final'].median(), 3)
dp_uf = round(mdo_df.groupby('UF')['Preço.Final'].std(ddof=1), 3)
vr_uf = round(mdo_df.groupby('UF')['Preço.Final'].var(ddof=1), 3)
amp_abs_uf = round(mdo_df.groupby('UF')["Preço.Final"].max() - mdo_df.groupby('UF')["Preço.Final"].min(), 3)
amp_rel_uf = round((amp_abs_uf /  media_uf)* 100, 3)
iqr_uf = round(mdo_df.groupby('UF')["Preço.Final"].quantile(0.75) - mdo_df.groupby('UF')["Preço.Final"].quantile(0.25), 3)

resumo_uf = pd.concat([
    freq_abs_uf.rename("Frequência Absoluta"),
    freq_rel_uf.rename("Frequência Relativa"),
    media_uf.rename("Média"),
    mediana_uf.rename("Mediana"),
    dp_uf.rename("Desvio Padrão"),
    vr_uf.rename("Variância"),
    amp_abs_uf.rename("Amplitude Absoluta"),
    amp_rel_uf.rename("Amplitude Relativa"),
    iqr_uf.rename("IQR")
], axis=1)

resumo_uf["Frequência Relativa"] = resumo_uf["Frequência Relativa"].astype(str) + "%"
resumo_uf["Amplitude Relativa"] = resumo_uf["Amplitude Relativa"].astype(str) + "%"

display(resumo_uf)

"""Todas as UFs tem a mesma frequência"""

mdo_df.groupby('UF')[["UNIDADE", "REF", "PEI"]].agg(lambda x:pd.Series.mode(x))

outliers_uf = outliers_geral.groupby('UF').size()
print(f"Quantidade de outliers por UF:\n{outliers_uf}")

"""Praticamente a mesma quantidade de outliers por UF"""

plt.figure(figsize=(15, 20))
sns.lineplot(
    data=mdo_df,
    x="REF",
    y="Preço.Final",
    hue="UF",
    palette="hls",
    style="UF",
    markers=True,
    dashes=False,
    errorbar=None
)

plt.xticks(rotation=45)
plt.title("Evolução do preço da mão de obra por unidade federativa")
plt.xlabel("Meses")
plt.ylabel("Preço")
plt.legend(fontsize=15)
plt.tight_layout()
plt.show()

"""RS e SC: alta mais acentuada
AC, RO e PI: crescimento baixo, ampliando a distância
PE e RN: variação irregular
SP e DF: crescimento estável
"""

plt.figure(figsize=(12,8))
sns.barplot(data=mdo_df, x="UF", y="Preço.Final", estimator="mean")
plt.title("Preço médio por unidade federativa de mão de obra")
plt.xlabel("Unidade federativa")
plt.ylabel("Preço médio")
plt.show()

"""Maiores médias: SP, MG, RJ, PR e ES"""

plt.figure(figsize=(12,8))
sns.barplot(data=resumo_uf, x="UF", y="Desvio Padrão")
plt.title("Desvio padrão do preço por unidade federativa de mão de obra")
plt.xlabel("Unidade federativa")
plt.ylabel("Desvio padrão")
plt.show()

"""Desvio padrão igual por UF

# Análise final dos dados

Por região, a média é parecida, mas é maior para a região Sudeste e menor para a região Centro-Oeste; a média do Sudeste é 2542, e a do Centro-Oeste é de 2361. Todas as medianas por região são distantes da média, o que dá um indicativo de dispersão nos dados. O desvio padrão de todos os dados é mais alto que a média, o que indica altíssima dispersão, mas sendo ainda maior no Sudeste e no Nordeste. Os valores gerais são: média 2425.561, mediana 1625.06, e desvio padrão 3424.958. A grande maioria dos preços nos dados gerais está entre o primeiro quartil e a mediana. Os preços gerais se concentram muito em valores mais baixos, até 2.500.

Observa-se aumento dos preços de forma ascendente de janeiro de 2022 até julho de 2024, com pequenas quedas em julho de 2022 e julho de 2023. Os preços aumentaram bastante temporalmente para a região Centro-Oeste, atingindo os patamares do Norte e quase do Nordeste em julho de 2024. O Nordeste parece ser o que tem a evolução mais estável, sem muitos picos. Os preços do Sudeste e do Sul são mais altos, apesar de a tendência de evolução ser a mesma para todas as regiões. Apesar de seguirem a tendência geral de alta, alguns estados apresentaram aumentos mais acentuados ao longo do tempo, como RS e SC, que partem de valores médios e se aproximam do topo no final do período. AC, RO e PI mostram um crescimento baixo, ampliando a distância em relação às UFs no topo. Além disso, algumas curvas, como a de PE e RN, mostram variações mais irregulares, enquanto outras, como SP e DF, sobem de forma mais estável.

Nordeste e Norte têm maior concentração de valores abaixo de 5.000. No boxplot, vemos novamente uma grande dispersão dos dados, e caixas levemente mais altas no Sudeste, e medianas levemente mais altas no Sul e Sudeste. Apesar da alta dispersão do Sudeste, ele não é uma das regiões com maiores números de outliers; as maiores são Nordeste e Norte (talvez pela presença de valores muito baixos, enquanto a dispersão grande do Sudeste esteja em valores mais altos, mas com quantidades menores de valores altos). Outro ponto importante é que, como Nordeste e Norte tem mais estados, e os estados tem praticamente a mesma quantidade de outliers, é esperado que essas regiões tenham quantidades mairoes de outliers.

A região Nordeste é a mais frequente no tipo de insumo mão de obra, ou seja, a que mais demanda mão de obra (mas ela também é a que tem mais estados, e a frequência por UF é igual para todas as UFs, então essa frequência maior decorre disso). O heatmap e a correlação de preços é 100%, pois eles são iguais. O heatmap e a correlação de preço final com zscore também é 100%, já que o zscore é só uma normalização dos valores do preço final.

Os estados com maiores médias são São Paulo, Minas Gerais, Rio de Janeiro, Paraná e Espírito Santo. O desvio padrão é muito parecido por UF.
"""